### ISSUE TITLE
Hud Editor Hotbar Bug

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHack-Recode#1]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/86876065/3313127c-2bd3-45fd-b622-aced3964d937)
No hand item

**Comment by NCPUser** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/86876065/bd9d9c77-a204-4ebc-97f3-270e3bd0b575)
no hotbar

**Comment by Pan4ur** [comment]
Fixed
