### ISSUE TITLE
ability to change the mouse button in kill aura

### ISSUE THREAD

**Issue by ilyadex** [Pan4ur/ThunderHack-Recode#101]
add so you can change the mouse button kill aura will be awesome for kill aura and can be done for hvh not only on swords but also in other modes for example
CS:GO
Stalker
(it uses the right mouse button to shoot)

**Comment by Pan4ur** [comment]
Aimbot -> mode CSGO

**Comment by ilyadex** [comment]
а там есть авто стрельба

**Comment by Pan4ur** [comment]
Есть

**Comment by ilyadex** [comment]
ебой

**Comment by ilyadex** [comment]
кстати а аим бот работает с анти аимом просто я ебаться с этой не хочу
