### ISSUE TITLE
Custom language in main menu

### ISSUE THREAD

**Issue by Smug2f** [Pan4ur/ThunderHack-Recode#108]
when you load th+ for the first time you can select in wich language the gui is (english / russia)  , but in the custom main menu there is only english language can't we add a translation file in the asset of client as a json that you can modify to get wich language you want? for example 
   "menu.singleplayer": "Соло",
    "menu.multiplayer": "многопользовательский",
    "menu.settings": "Настройки",
    "menu.clickgui": "Gui",
    "menu.exit": "выход"

**Then we load the translation using:**
String translatedSingleplayerLabel = I18n.translate("menu.singleplayer");
String translatedMultiplayerLabel = I18n.translate("menu.multiplayer");
String translatedSettingsLabel = I18n.translate("menu.settings");
String translatedClickguiLabel = I18n.translate("menu.clickgui");
String translatedExitLabel = I18n.translate("menu.exit");
l18n is mc game language setting 

**And finally you use the translated strings:**
buttons.add(new MainMenuButton(-110, -70, translatedSingleplayerLabel, () -> mc.setScreen(new SelectWorldScreen(this)));
buttons.add(new MainMenuButton(4, -70, translatedMultiplayerLabel, () -> mc.setScreen(new MultiplayerScreen(this)));
buttons.add(new MainMenuButton(-110, -29, translatedSettingsLabel, () -> mc.setScreen(new OptionsScreen(this, mc.options)));
buttons.add(new MainMenuButton(4, -29, translatedClickguiLabel, () -> mc.setScreen(ClickUI.getClickGui()));
buttons.add(new MainMenuButton(-110, 12, translatedExitLabel, () -> mc.scheduleStop()));

***I'm not russian but i would translate it into another language***
(ps :i don't know if it will work)

**Comment by 06ED** [comment]
added
