### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by I-No-oNe** [Pan4ur/ThunderHack-Recode#110]
> - https://mclo.gs/DHczqGH
```yml
- Hope it will help
```

**Comment by Pan4ur** [comment]
I think it's problem with sodium

**Comment by I-No-oNe** [comment]
Will u fix the problem?(so thunder hack will be compatible with sodium?)

**Comment by Pan4ur** [comment]
Is it compatible with sodium, what version do you have?

**Comment by Pan4ur** [comment]
did you figure out the problem?

**Comment by I-No-oNe** [comment]
***Nope*** 
> (BTW, there are some still random crashes. Do you want me to send my logs every time it's happening? )
