### ISSUE TITLE
Too Laggy For My Computer

### ISSUE THREAD

**Issue by user9348937585686867** [Pan4ur/ThunderHack-Recode#119]
no, this is not a bug, but it would be great to add a option that removes rgb and the details, the reason why is beacause there are many people who can only afford a computer that is barrely past potato pc, and im in it.

**Comment by user9348937585686867** [comment]
just please. add it

**Comment by Pan4ur** [comment]
colors don't affect performance, just reduce the number of visual modules and start using LegacyHud
