### ISSUE TITLE
Grim Velocity

### ISSUE THREAD

**Issue by Botter16** [Pan4ur/ThunderHack-Recode#12]
Velocity под грим детектит жестко

**Comment by Pan4ur** [comment]
На каком сервере

**Comment by Botter16** [comment]
> На каком сервере

На любом где грим. Холик, аресмайн и т.д.

**Comment by Botter16** [comment]
В FDPClient есть похожий обход, как у тебя. Но какой-то чел написал про это и его пофиксили.

**Comment by Botter16** [comment]
> В FDPClient есть похожий обход, как у тебя. Но какой-то чел написал про это и его пофиксили.

https://github.com/GrimAnticheat/Grim/issues/1056

**Comment by NCPUser** [comment]
> > На каком сервере
> 
> На любом где грим. Холик, аресмайн и т.д.

Аресмайн это Intave B14 т.к робит флай на лодке

**Comment by Pan4ur** [comment]
ну хз хз
