### ISSUE TITLE
MINECRAFT CRASHING when i enable the module "auto web"

### ISSUE THREAD

**Issue by tikdkwkdowokdw** [Pan4ur/ThunderHack-Recode#125]
**Describe the bug**

**To Reproduce**

> 

**Expected behavior**

**Screenshots**
[crash-2023-10-28_22.15.44-client.txt](https://github.com/Pan4ur/ThunderHack-Recode/files/13204135/crash-2023-10-28_22.15.44-client.txt)

**Additional context**

**Comment by Pan4ur** [comment]
Handled in discord
