### ISSUE TITLE
middleclick firework on elytra

### ISSUE THREAD

**Issue by pinktinymeat** [Pan4ur/ThunderHack-Recode#140]
сделайте так чтобы можно было юзать фейерверки на элитре нажимая на кнопку колесика мыши или чтобы можно было выбрать любую кнопку для этого
мне не удобно постоянно щелкать туда-сюда слоты когда я на элитрах лечу за кем-то и хочу его одновременно и бить и летать фейером дальше![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/150605701/dcda1965-23f2-4e6c-8296-1011a2deb27e)

**Comment by Pan4ur** [comment]
Там вроде как короче велючаеш елитрасвап

**Comment by Pan4ur** [comment]
Пон да потом рыжым меняиш не помню как называеца но там настройкы скрытые вылазиют

**Comment by Pan4ur** [comment]
И там биндиш фейерверк
