### ISSUE TITLE
new module bind system

### ISSUE THREAD

**Issue by master7720** [Pan4ur/ThunderHack-Recode#143]
the new one is ass it just doesnt work for me i middle click nothing happens just add a bind system into the module :/

**Comment by master7720** [comment]
also doing @bind modulename LCtrl doesnt work at all gives me a error "there is no such button"

**Comment by Pan4ur** [comment]
Just click on the mouse wheel and press the button you want to bind the mod to, there is nothing to break, the bind system has not changed

**Comment by master7720** [comment]
> Just click on the mouse wheel and press the button you want to bind the mod to, there is nothing to break, the bind system has not changed

it just doesnt work for me

**Comment by Pan4ur** [comment]
I have no idea, it works for others
