### ISSUE TITLE
штуки

### ISSUE THREAD

**Issue by pinktinymeat** [Pan4ur/ThunderHack-Recode#145]
привет

1. сделайте пожалуйста так чтоб пёрдчасер кидал перлы ток за тем с кем я пвп типо отслеживал ник его и онли за ним кидал, там по хитам или я хз как вам виднее (_я пехался с челом и рядом чувак рандом бежит, этот рандом кидает перл и перлчасер кидает перл за этим рандомом и итог я потерял того с кем пехался_) и чтобы он кидал перлы только тогда когда я на земле стою иначе если в прыжке кинуть то он либо вниз в блок кинет либо перекинет. и хотелось бы чтобы он еще и из инвентаря перлы мог юзать (_и не редко бывает такое что он вообще просто не кидает перл_) 

2. добавьте в нюкер настройку чтобы можно было скрыть ошметки от сломанных блоков (_если нюкером шотать блоки в аду то всё лицо в этих опилках и это мешает_)

3. и еще, я заметил что иногда киллаура будто бы начинает ловить цель только когда подойдешь к ней прямо в упор, если посмотреть на то как с целестиалом или нурланом на тех же элитрах можно пехаться то тут так не получается почему-то, как и дать первый хит тоже не всегда выходит особенно если хвх. в целестиале или рунсултане киллаура если на элитрах таргетить чуваков то киллаура (_особенно в целесте_) идеально каждый хит бьет чувака за которым я летаю даже если я и он в полете на элитрах (_я хз мб это из-за того что там можно настроить радиус прицела килки, или мб сделать так чтоб килка анализировала всех вокруг и заранее понимала на кого ей щас придется тригериться чтобы она не думала вначале,(под "триггериться" я щас имел в виду начала процесса прицеливания а потом когда 3 блока до игрока то уже бить и тип вот это всё вместе). ну или что-то вроде этого проверить в ней, но опять же вам виднее, мне показалось что я могу сюда это написать_)

4. и мб это невозможно но все же я был бы счастлив если бы вы попытались где-то найти или слелать что-то новое для ач grim (_акб и бхопы или стрейфы если такие существуют_) и вроде как в нурсултане есть в акб много грим режимов и один из них это фулл 0 акб но которое работает только на удары от игроков (_то есть от шипов и прочего оно откидывает, а вот если удар от игрока то нет_). я не знаю но я слышал что это много где до сих пор работает🤷🏾‍♂️
Мой текст насчет акб из нурсултана может оказаться полной туфтой и устаревшим очком <--- и если это так то плюньте в меня умоляю...

🥸если вы хз что ответить то просто закройте этот пост и когда появится возможность и если вам не будет лень то постарайтесь хотябы что-то из этого поискать/исправить или улучшить🙂 и спс вам за чит это самый лучший мод на майнкрафт!  все бомжи с метеором смотрят на меня как на НЛО с вот такими вот глазами "😳" и молятся как обезьяны на молнию! 🙉⚡️ 
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/150605701/516e0795-1c4b-4caf-b3ed-ed75d839df73)

**Comment by Pan4ur** [comment]
1, 2 в процессе, 3 если у тебя режим Interact то так и должно быть, 4 в нурике банит с пары ударов на фт
