### ISSUE TITLE
чтоб киляура сама определяла максимально возможное расстояние удара

### ISSUE THREAD

**Issue by pinktinymeat** [Pan4ur/ThunderHack-Recode#153]
сделать как в coffee client чтоб можно было не только вручную настраивать расстояние в килке но и чтоб был режим "авто" в котором она сама будет определять максимальное расстояние и бить на максимально возможном ей расстоянии там где может сам дотянуться человек

 (очень нужно когда чел сверху или снизу и киллаура не может до него достать не смотря на то что сам вручную ты его можешь бить ну ты пон крч)
 (или когда чел убегает то иногда килка не может его бить а если сам будешь пытаться ударить то ты можешь но кишка почему-то иногда не дотягивается ну ты пон х2)

**Comment by nepcNK** [comment]
типа шоб типов ливающих на элитрах бить типа?
