### ISSUE TITLE
Crushing when i press f1-f9

### ISSUE THREAD

**Issue by GhostMikz** [Pan4ur/ThunderHack-Recode#16]
edit: crash*.

**Comment by Pan4ur** [comment]
Сan you send me a crashlog?

**Comment by GhostMikz** [comment]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-07-29 16:21:10
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.class_761.redirect$bef000$thunderhack$replaceShaderHook(class_761.java:9441)
	at net.minecraft.class_761.method_22710(class_761.java:1401)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "thunder.hack.utility.interfaces.IShaderEffect.addFakeTargetHook(String, net.minecraft.class_276)" because the return value of "thunder.hack.utility.render.shaders.OutlineProgram.getShader()" is null
	at thunder.hack.utility.render.shaders.ShaderManager.lambda$static$0(ShaderManager.java:9)
	at thunder.hack.utility.render.shaders.OutlineProgram.<init>(OutlineProgram.java:31)
	at thunder.hack.utility.render.shaders.OutlineProgram.create(OutlineProgram.java:36)
	at thunder.hack.utility.render.shaders.ShaderManager.<clinit>(ShaderManager.java:8)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_761.redirect$bef000$thunderhack$replaceShaderHook(class_761.java:9441)
	at net.minecraft.class_761.method_22710(class_761.java:1401)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 28 total; [class_746['GhostMikz'/8326, l='ClientLevel', x=0.20, y=64.27, z=143.89], class_745['mellonate543'/8299, l='ClientLevel', x=-7.27, y=59.00, z=137.13], class_745['AhmetBeYY'/8300, l='ClientLevel', x=-33.68, y=64.38, z=135.56], class_745['renso12345'/8259, l='ClientLevel', x=-12.93, y=59.00, z=129.79], class_745['survivalaqua'/211, l='ClientLevel', x=-7.50, y=59.00, z=132.50], class_745['parkour'/251, l='ClientLevel', x=-9.50, y=60.00, z=111.50], class_745['SFXFighter'/8342, l='ClientLevel', x=4.12, y=60.00, z=140.37], class_745['Maksbuff'/8344, l='ClientLevel', x=-8.00, y=59.00, z=143.78], class_745['Deamboy1735'/8349, l='ClientLevel', x=-28.21, y=69.61, z=132.51], class_745['geetansh2008'/8352, l='ClientLevel', x=-12.14, y=59.00, z=126.84], class_745['piesio8'/8354, l='ClientLevel', x=-33.01, y=64.00, z=132.51], class_745['arcade'/203, l='ClientLevel', x=-6.50, y=60.00, z=112.50], class_745['skywars'/207, l='ClientLevel', x=-2.50, y=60.00, z=114.50], class_745['duels'/255, l='ClientLevel', x=1.50, y=60.00, z=116.50], class_745['factions'/247, l='ClientLevel', x=3.50, y=60.00, z=144.50], class_745['creative'/259, l='ClientLevel', x=3.50, y=60.00, z=120.50], class_745['survival'/239, l='ClientLevel', x=6.50, y=60.00, z=132.50], class_745['prison'/227, l='ClientLevel', x=5.50, y=60.00, z=140.50], class_745['survival3'/263, l='ClientLevel', x=5.50, y=60.00, z=124.50], class_745['survival2'/235, l='ClientLevel', x=6.50, y=60.00, z=128.50], class_745['skyblock'/231, l='ClientLevel', x=6.50, y=60.00, z=136.50], class_745['oneblock'/243, l='ClientLevel', x=1.50, y=60.00, z=148.50], class_745['bedwars'/215, l='ClientLevel', x=-2.50, y=60.00, z=150.50], class_745['kitpvp'/219, l='ClientLevel', x=-6.50, y=60.00, z=152.50], class_745['EFTB'/223, l='ClientLevel', x=-9.50, y=60.00, z=153.50], class_745['TanqR_Dark'/8358, l='ClientLevel', x=-26.42, y=62.19, z=132.51], class_745['Hell_Raider'/149, l='ClientLevel', x=-2.20, y=60.17, z=134.71], PlayerCopyEntity['GhostMikz'/150, l='ClientLevel', x=-2.20, y=60.17, z=134.71]]
	Chunk stats: 1024, 109
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,64,0), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 32755396 game time, 6000 day time
	Server brand: MineMalia
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/§fGene§8sys§7 Pack §f§l1.17.1.zip, file/Boosted FPS.zip

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 373337088 bytes (356 MiB) / 738197504 bytes (704 MiB) up to 3154116608 bytes (3008 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
	Identifier: Intel64 Family 6 Model 142 Stepping 12
	Microarchitecture: Whiskey Lake
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce MX130
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x174d
	Graphics card #0 versionInfo: DriverVersion=31.0.15.2879
	Graphics card #1 name: Intel(R) UHD Graphics 620
	Graphics card #1 vendor: Intel Corporation (0x8086)
	Graphics card #1 VRAM (MB): 1024.00
	Graphics card #1 deviceId: 0x3ea0
	Graphics card #1 versionInfo: DriverVersion=27.20.100.9664
	Memory slot #0 capacity (MB): 4096.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 4096.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 11780.53
	Virtual memory used (MB): 9531.95
	Swap memory total (MB): 3712.00
	Swap memory used (MB): 497.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		alternate-current: Alternate Current 1.7.0
		betterbeds: Better Beds 1.3.0
		dynamicfps: Dynamic FPS 2.4.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		entityculling: EntityCulling-Fabric 1.6.2-mc1.20
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.39+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.20+b3afc78b77
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-models-v0: Fabric Models (v0) 0.3.35+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.1.0+c154966e77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.4.0+c154966e77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.44+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.47+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.6+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.6+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric_hider: Fabric Hider 1.6.2+1.18.2
		fabricloader: Fabric Loader 0.14.21
		fadeless: Fadeless 1.0.1
		ferritecore: FerriteCore 6.0.0
		immediatelyfast: ImmediatelyFast 1.1.15+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
			net_lenni0451_reflect: Reflect 1.1.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		memoryleakfix: Memory Leak Fix 1.1.1
		minecraft: Minecraft 1.20.1
		smoke_suppression: Smoke Suppression 1.0.16
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		sodium: Sodium 0.4.10+build.27
		sodium-extra: Sodium Extra 0.4.23+mc1.20.1-build.106
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		thunderhack: ThunderHack 3.0
	Launched Version: fabric-loader-0.14.21-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Intel(R) UHD Graphics 620 GL version 3.2.0 - Build 27.20.100.9664, Intel
	Window size: 1366x768
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=0, source=SHADER COMPILER, type=ERROR, severity=HIGH, message='SHADER_ID_COMPILE error has been generated. GLSL compile failed for shader 22, "": ERROR: 0:63: 'f' : syntax error syntax error

' x 1
	Using VBOs: Yes
	Is Modded: Probably not. Client jar signature and brand is untouched
	Type: Client (map_client.txt)
	Graphics mode: fast
	Resource Packs: vanilla, fabric, file/§fGene§8sys§7 Pack §f§l1.17.1.zip (incompatible), file/Boosted FPS.zip (incompatible)
	Current Language: en_us
	CPU: 8x Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz

**Comment by Pan4ur** [comment]
does it crash when just f* or f* + fn?

**Comment by GhostMikz** [comment]
i think not

**Comment by GhostMikz** [comment]
oh i read it wrong i think its both of them

**Comment by Pan4ur** [comment]
try 1.2b290723
