### ISSUE TITLE
штуку чтоб чужие кфг ставились без изменений собственных биндов и визуалов

### ISSUE THREAD

**Issue by pinktinymeat** [Pan4ur/ThunderHack-Recode#162]
идея добавить функцию чтоб при ее включении когда я загружал чужой кфг то чтобы у меня менялись бы только настройки всяких функций (тип чтоб менялись только настры киллауры, акб, спидов и т.п.), а визуалы чтобы наоборот никак не изменялись (тип визуалы по типу ESP, nametags, itemesp, hudeditor, clickgui и чтоб абсолютно ВСЕ визуалы оставались неизменными). А и еще чтобы бинды не трогались. Иначе когда скачиваешь чужой кфг чтоб его потестить то постоянно перед тем как с ним поиграть приходится целый час сидеть и настраивать всё назад так как было раньше... (перебиндивать функции, настраивать расположение вещей в hudeditor, неймтаги,есп и прочее).

я не знаю как это можн реализовать но наверное можно прост сделать функцию включив которую можно будет залокать все бинды и визуальные составляющие и спокойно грузить чужие кфг. тип будут меняться ток настры всех combat movement misc player функций, а визуалы(и бинды) будут локнуты. ТОП. таким способом все смогут спокойно грузить чужие кфг и не ебаться с визуалами блять по часу, и не вспоминать что и на что было забинжено в своём уже привычном личном конфиге. лайк 👍🏿
 
Лично мне эта функция была бы НЕ бесполезной.

спасибо 😶

**Comment by Pan4ur** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/82473048/c513dc4f-d620-4c90-8505-a06818e9699f)
