### ISSUE TITLE
Add smart to speedmine

### ISSUE THREAD

**Issue by Epic62790** [Pan4ur/ThunderHack-Recode#17]
This should be a feature

**Comment by Pan4ur** [comment]
What is it

**Comment by Epic62790** [comment]
its from earthh4ck

**Comment by Pan4ur** [comment]
I really don't see any difference from a regular packetmine

**Comment by Epic62790** [comment]
is slientswitch implemented

**Comment by Pan4ur** [comment]
For cc/strict
