### ISSUE TITLE
Cooldown optimization for Aura/Оптимизация времени затухания ауры

### ISSUE THREAD

**Issue by Anonimouze** [Pan4ur/ThunderHack-Recode#173]
English: When the enemy is almost dead, there is not always the need to wait for the cooldown in order to kill the enemy. So this option would optimize the cooldown of Aura the give the minimum amount of damage to kill the enemy as fast as possible.
Russian: Когда враг уже почти мертв, не всегда есть необходимость дожидаться кулдауна, чтобы убить противника. Таким образом, эта опция позволит оптимизировать кулдаун ауры, чтобы нанести минимальное количество урона и убить врага как можно быстрее.

**Comment by Pan4ur** [comment]
Это бесполезно (я уже это проверял)

**Comment by Anonimouze** [comment]
Что? Как это бесполезно? Иногда игрок находится в 1 сердце без тотема, а аура все еще ждет полного кулдауна. Или что вы не можете сделать это?
