### ISSUE TITLE
Aura -> LegitAura, Aura -> ElytraFix,

### ISSUE THREAD

**Issue by 0xhardcoder** [Pan4ur/ThunderHack-Recode#178]
Add legit mode to Aura
Add FOV slider to Aura legit mode
Add Smoothness slider to Aura legit mode
Fix Aura when using an elytra

**Comment by Pan4ur** [comment]
ElytraFix?

**Comment by 0xhardcoder** [comment]
Aura is missing when flying with elytra

**Comment by Anonimouze** [comment]
> Aura is missing when flying with elytra

That ain't fixable because it may be because of your ping, bad config or the servers anticheat.

**Comment by 0xhardcoder** [comment]
Also Aura ShieldBreaker not switching to axe and it looks like i broke the shield with a sword.

**Comment by Anonimouze** [comment]
> Also Aura ShieldBreaker not switching to axe and it looks like i broke the shield with a sword.

Yeah. Its probably intentional.
