### ISSUE TITLE
Does not work cheat client with mod ViaFabricPlus 3.0.2.

### ISSUE THREAD

**Issue by Sezzoqiq** [Pan4ur/ThunderHack-Recode#179]
Does not work cheat client with mod ViaFabricPlus 3.0.2. With the usual ViaFabric works but in it the problem that when you go to some servers it agrit anti-cheat, gives an error kicks out and so on.
[tl-logger11111369586256905382.txt](https://github.com/Pan4ur/ThunderHack-Recode/files/13772239/tl-logger11111369586256905382.txt)

**Comment by Pan4ur** [comment]
Выруби обоссаные скины ely.by в настройках легаси в рот еблегаси
