### ISSUE TITLE
arraylist bug

### ISSUE THREAD

**Issue by HashNotAsh** [Pan4ur/ThunderHack-Recode#180]
**Describe the bug**
arraylist stuck on the side outside my screen

**To Reproduce**
idk

**Expected behavior**
me being able to move it over back (i cant thats why im reporting the bug)

**Screenshots**
https://www.mediafire.com/file/7wkgnbdixxmuiul/2023-12-27_23.41.07.png/file
imgur sucks so

**Additional context**
i just installed thunderhack recode so its a clean file
also im using the crystalpvp.cc config
extra help here too can i download the other configs than only one or none or not because i cant seem to be able to do so

**Comment by HashNotAsh** [comment]
nevermind i literally just got it i am dumb
can you explain how to download the other configs other than the crystalpvp.cc one before closing pls thanks

**Comment by Pan4ur** [comment]
@cfg set <name>, if you want default configs, download it from https://github.com/Pan4ur/ThunderHack-Recode/tree/main/src/main/resources/cfg
