### ISSUE TITLE
баг + идея

### ISSUE THREAD

**Issue by pinktinymeat** [Pan4ur/ThunderHack-Recode#181]
1. фикс автототем - когда я падаю у меня берется в руку тотем, но, когда я одном пикселе от земли - автототем опять убирается из руки и я дохну.. (у меня вокруг дома моего везде снег и мб он триггерится на блок снега который как ковер и убирает тотем я хз но все же проверьте это с обычными блоками и снегом с коврами прошу)

2. сделайте так чтобы PauseWhileEating в киллауре не бил когда с помощью автогепла естся яблоко находящееся в левой руке. Я играю на сервере где ты не можешь моментально кушать гепл после удара это сделано чтобы софты не могли одновременно жрать и бить. Мне нужно чтобы киллаура переставала бить когда автогепл начинает кушать левой рукой яблочко и затем опять начинала бить когда яблоко уже скушано. Просто неудобно вырубать киллауру, кушать и потом опять врубать, или бить киллаурой и щелкать основной рукой на слот с яблоком и вручную кушать его а потом опять слот с мечем тоже запаривает.. прошу помогите сделайте это

**Comment by Anonimouze** [comment]
Бесполезное предложение, разработчики уже отказались от клиента (я думаю).

**Comment by Anonimouze** [comment]
Это предложение не будет полезным, разработчики уже отказались от клиента (я думаю).

**Comment by nepcNK** [comment]
> Это предложение не будет полезным, разработчики уже отказались от клиента (я думаю).

он думает если че

**Comment by Pan4ur** [comment]
Я тоже думаю
