### ISSUE TITLE
Probably chat related bug

### ISSUE THREAD

**Issue by PrimeTDMomega** [Pan4ur/ThunderHack-Recode#182]
**Describe the bug**
Whenever I join cc after a while it just kicks me with a massive error message.

**To Reproduce**
1. Just using preset cc config
2. Enter CC
3. Kicked

**Expected behavior**

**Screenshots**
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/105910256/94169f54-7a81-4411-87f4-47868dc15ddf)

**Additional context**

**Comment by Pan4ur** [comment]
Download latest ViaFabricPlus and select 1.20.1
