### ISSUE TITLE
autobuy

### ISSUE THREAD

**Issue by RayZLove** [Pan4ur/ThunderHack-Recode#184]
Я часто пишу про него, но щас с выходом обновления FunTime автобай стал еще хуже, он ловит шмотку 1 раз после чего замораживается, и ничего не покупает, постоянно фейкует
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/91051371/a0a645c5-8bc1-4ef1-ab84-4f7d00f9560f)
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/91051371/5ddc75b0-f67a-46ff-ae33-bf67c68d6f31)
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/91051371/a9c045c8-44f6-41af-bb36-9aad868b6f58)

Его не кикает и не банит, он просто не ловит предметы

**Comment by aabababbabajscookie** [comment]
+

**Comment by RayZLove** [comment]
Будет ли фикс ?

**Comment by KirillJPG** [comment]
слава науке автотопка умерла, слава пионеру!!
