### ISSUE TITLE
NewChunks

### ISSUE THREAD

**Issue by RealmKebab** [Pan4ur/ThunderHack-Recode#188]
**Is your feature request related to a problem? Please describe.**
you see, every anarchy-based clients like meteor and lambda have newchunks

**Describe the solution you'd like**
add newchunks module since very useful for anarchys ervrs

**Comment by master7720** [comment]
> **Is your feature request related to a problem? Please describe.** you see, every anarchy-based clients like meteor and lambda have newchunks
> 
> **Describe the solution you'd like** add newchunks module since very useful for anarchys ervrs

fun fact meteor does not have new chunks and lambda is for 1.12.2 i think the reason alot of fabric clients dont have the new chunks module is because on how inefficient is it now

**Comment by Pan4ur** [comment]
Yes, NewChunks don't work anymore, we need new methods such as defining new ores or comparing chunk loading times, but I can't get around to doing that
