### ISSUE TITLE
AutoBuy

### ISSUE THREAD

**Issue by OnInStay** [Pan4ur/ThunderHack-Recode#193]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/156786195/4238a507-5c2a-4104-b8f4-7a842f7729d8)
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/156786195/f312a472-a2d5-4351-939e-2f6ec9235f11)

Через чур часто фейкует за ночь поймал только 3 незер шмотки, позавчера все работало прекрасно, так же на фантайме есть новогодний подарочек который помечен снежинкой ❄ было бы прикольно если бы вы сделали бы возможность проверки снежинки

![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/156786195/1073b68f-0679-46db-87bd-44a9f503468a)

**Comment by Boneshadow** [comment]
Согласен, тоже заметил что мого фейков стало

**Comment by RayZLove** [comment]
Кста да вчера еще заметил
