### ISSUE TITLE
Bug with Pearl block throw

### ISSUE THREAD

**Issue by SmithAndwessonKnife** [Pan4ur/ThunderHack-Recode#196]
**Describe the bug**

**To Reproduce**
1. Go to Pearl block throw
2. Click on pearl block throw twice
3. game crashes
4. The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_6128()" because "thunder.hack.modules.movement.NoFall.mc.field_1724" is null
![image_2024-01-16_211644022](https://github.com/Pan4ur/ThunderHack-Recode/assets/155413271/d8da4038-a289-435f-8b1f-7037a0d12ef4)

**Expected behavior**

**Screenshots**
[crash-2024-01-16_21.12.56-client.txt](https://github.com/Pan4ur/ThunderHack-Recode/files/13958161/crash-2024-01-16_21.12.56-client.txt)

**Additional context**

**Comment by Pan4ur** [comment]
Try to use latest version
