### ISSUE TITLE
A version for 1.20.2

### ISSUE THREAD

**Issue by TheAnonymousXAlt** [Pan4ur/ThunderHack-Recode#197]
I would like a version that is 1.20.2

**Comment by RayZLove** [comment]
Hello, you can use ViaVersion/ ViaFabricPlus, to upgrade to an older version
click [here](https://github.com/ViaVersion/ViaFabricPlus/releases) to download

![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/91051371/745c7b46-90c7-4c14-a302-fa5801ad26d8)

**Comment by TheAnonymousXAlt** [comment]
Like, to add a version I can use with other 1.20.2 mods.
