### ISSUE TITLE
Couldn't display unicode texts

### ISSUE THREAD

**Issue by TanChenyu** [Pan4ur/ThunderHack-Recode#210]
**Expected behavior**
I think it can show unicode texts as usual.
Maybe you need to add an unicode font.
Or make the "Back to main menu" as a config.

**Screenshots**
![pic](https://github.com/Pan4ur/ThunderHack-Recode/assets/73740771/361b671e-19c2-44df-92ff-251266138371)

**Comment by Pan4ur** [comment]
What is your language in Minecraft?

**Comment by TanChenyu** [comment]
> What is your language in Minecraft?

Simplified Chinese

**Comment by Pan4ur** [comment]
Your language is not supported by our font, go to the "ClientSettings" module and disable "CustomMainMenu"

**Comment by TanChenyu** [comment]
> Your language is not supported by our font, go to the "ClientSettings" module and disable "CustomMainMenu"

Thanks!
