### ISSUE TITLE
Can't move HUD elements

### ISSUE THREAD

**Issue by yuxiangll** [Pan4ur/ThunderHack-Recode#228]
![3780359714](https://github.com/Pan4ur/ThunderHack-Recode/assets/108518874/f028eb5d-2ad8-42eb-b389-e4ae0d50930a)
All the elements overlap in the same place and I can't move them,

java17
MacOS M2

please help me

**Comment by Pan4ur** [comment]
It’s m2 issue, try to enable ClientSettings -> ScaleFactorFix
