### ISSUE TITLE
хитмаркер (или как ее назвать)

### ISSUE THREAD

**Issue by CvatiyMlinec** [Pan4ur/ThunderHack-Recode#234]
добавь в рендер фигню которая показывает у чела сколько хп зарегенилось / отнялось я думаю будет прикольно выглядеть вот пример 
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/138506119/acfa8e50-83f9-460f-8d2a-4c1696c93d7e)

**Comment by IKronos123** [comment]
> хуйня

мать твоя хуйня

**Comment by Kowwwk** [comment]
> > хуйня
> 
> мать твоя хуйня

иди нахуй пидорок крашенный

**Comment by Pan4ur** [comment]
щас бы трешкаться на гитхабе

**Comment by IKronos123** [comment]
> > > хуйня
> > 
> > 
> > мать твоя хуйня
> 
> иди нахуй пидорок крашенный

пошел нахуй долбаеб сын мусоропровода

**Comment by nepcNK** [comment]
кошк
