### ISSUE TITLE
scaffold needs better bypass

### ISSUE THREAD

**Issue by Elovenge** [Pan4ur/ThunderHack-Recode#243]
The current version has too few scaffolding options to bypass many anti-cheats, such as ncp.
Please add more options to scaffold to make it more customizable and bypass more anti-cheats.
(Maybe you can borrow scaffolds from other open source clients, such as fdp or kevin reborn)

**Comment by Elovenge** [comment]
> Anything but 1.8 clients........ you should've said to borrow from clients like LiquidBounce-Nextgen or something.

Seems like yes, I forgot about Liquidbounce Nextgen when I sent this issues...

**Comment by zone1889** [comment]
i ll second that
