### ISSUE TITLE
[IMPROVEMENT] Add a sub-option named 'Visible' in the 'ShieldBreaker' and 'UnpressShield' option in Aura

### ISSUE THREAD

**Issue by Anonimouze** [Pan4ur/ThunderHack-Recode#255]
Add a sub-option named 'Visible' in the 'ShieldBreaker' and 'UnpressShield' option in Aura, that when turned on will show those modules taking action in the client side too instead of doing it on server side only.

**Comment by Pan4ur** [comment]
there's no way to do that, and you don't need to
