### ISSUE TITLE
[IMPROVEMENT] Make the scoreboard and the module notifications a hud element

### ISSUE THREAD

**Issue by Ancnymous** [Pan4ur/ThunderHack-Recode#256]
Remove scoreboard from the norender options and make it a HUD element that can be moved around anywhere. That's going to be really useful when you need the scoreboard information. Also, make the notifications that display when you turn a module on or off possible to be turned on or off and movable through the HUD. That's because it always overlaps other HUD elements, such as the legacy HUD.

**Comment by Anonimouze** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/146366549/3ee1be30-9eb8-4059-a3fc-0929424ac064)
