### ISSUE TITLE
[IMPROVEMENT] Get the superknockback module outta LiquidBounce-nextgen >;)

### ISSUE THREAD

**Issue by Anonimouze** [Pan4ur/ThunderHack-Recode#263]
Get the superknockback module outta LiquidBounce-nextgen >;). I think you should not face much trouble this time as you have already got 'Rotation' module and the 'GrimEntity2' speed mode outta the client. This should be done because the current MoreKnockback module is almost useless on any anticheats as it flags you like crazy and also doesn't let you crit.

**Comment by larryngton** [comment]
since this module is useless for hvhing and is only useful for beating legits just go and use lb nextgen

this is an anarchy/hvh client, why would they need to update this?

**Comment by Anonimouze** [comment]
> since this module is useless for hvhing and is only useful for beating legits just go and use lb nextgen
> 
> this is an anarchy/hvh client, why would they need to update this?

And even if it is a completely anarchy based client, it will be useful on a server where the velocity is patched.

**Comment by zoskiinepaster** [comment]
bro, obxodi na fantaime uze ne aktualni

**Comment by zoskiinepaster** [comment]
v chite

**Comment by master7720** [comment]
ngl @Anonimouze all of ur PR's have been useless asf and most of ur issues are useless or completey dumb

**Comment by Anonimouze** [comment]
> ngl @Anonimouze all of ur PR's have been useless asf and most of ur issues are useless or completey dumb

XD look im so famous now I got haters XDDD. Thanks LMAO

**Comment by Anonimouze** [comment]
Anyways hating on ‘Anonymous’ wont do anything as it never did.

**Comment by master7720** [comment]
> Anyways hating on ‘Anonymous’ wont do anything as it never did.

dawg doesnt know anything abt Anonymous

**Comment by master7720** [comment]
> > ngl @Anonimouze all of ur PR's have been useless asf and most of ur issues are useless or completey dumb
> 
> XD look im so famous now I got haters XDDD. Thanks LMAO

no am just calling you out for being stupid
