### ISSUE TITLE
Auto crystal grim rotations flag for simulation.

### ISSUE THREAD

**Issue by sootysplash** [Pan4ur/ThunderHack-Recode#29]
From what I saw the autocrystal movement is out of sync with the rotations, so it would move incorrectly while rotating correctly.
Steps to reproduce since this is a bit hard to understand:
1: Get an autocrystal target
2: Enable crystal aura and get knocked back till you stop placing and breaking
3: Test your movement and rotate to see how it's incorrect

Even with these issues I applaud your efforts, I've not seen a single client even try to do this before.

**Comment by Pan4ur** [comment]
Its finally fixed
