### ISSUE TITLE
.

### ISSUE THREAD

**Issue by rampage1231** [Pan4ur/ThunderHack-Recode#292]
![изображение_2024-04-30_000214351](https://github.com/Pan4ur/ThunderHack-Recode/assets/168465600/ee77c264-5e8e-459d-8264-53bd29a0d758)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rampage1231** [comment]
Here is such a mistake

**Comment by Pan4ur** [comment]
crashlog?
