### ISSUE TITLE
we need better fps

### ISSUE THREAD

**Issue by zone1889** [Pan4ur/ThunderHack-Recode#293]
I need better optimization, I can only get 140~160 fps with thunder hack now, compared to 220~240 fps in the previous version, I hope to get good FPS while maintaining the bypass anti-cheat

**Comment by zone1889** [comment]
i7-13700kf
gtx 1660 s
8gb ×2

**Comment by Pan4ur** [comment]
Use sodium + exordium, it’s unlikely that anything else can be optimized in the client
