### ISSUE TITLE
OpenGL kick sodium

### ISSUE THREAD

**Issue by violentqm** [Pan4ur/ThunderHack-Recode#296]
**Describe the bug**
kicks for openlg cannot be accesed cuz of sodium

**To Reproduce**

1. Go to 'the cloud configs'
2. Load 'cc'
3. Have 'sodium'
4. turn on surrond and see error

**Expected behavior**
kick you every fucking second

**Screenshots**
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/79298794/57429662-3a3f-479d-b07a-6f412c73b521)

**Additional context**
nothing extra

**Comment by Pan4ur** [comment]
fixed
