### ISSUE TITLE
Remove satin

### ISSUE THREAD

**Issue by x76a** [Pan4ur/ThunderHack-Recode#300]
This mod reduces fps

**Comment by master7720** [comment]
if your talking about using the shader renders then use the mod sodium

**Comment by Pan4ur** [comment]
Without this mod, the shaders will not be able to work, are you sure satin reduces fps? How did you check it?

**Comment by Pan4ur** [comment]
Btw that turned out to be true

**Comment by I-No-oNe** [comment]
But why actually?
