### ISSUE TITLE
There is a small detail issue

### ISSUE THREAD

**Issue by Ninthless** [Pan4ur/ThunderHack-Recode#313]
**Describe the bug**
After using this client, breaking blocks under any circumstances will not produce particle effects

**To Reproduce**
Simply destroy the blocks to reproduce

**Expected behavior**
Please forgive my obsessive-compulsive disorder, I hope that after repairing, damage particles can appear in the damaged blocks

**Screenshots**
nothing

**Additional context**
Thank you

**Comment by Pan4ur** [comment]
NoRender -> BreakParticles

**Comment by Ninthless** [comment]
I did not enable the norender module, so the module was not enabled and it still takes effect

**Comment by Pan4ur** [comment]
fixed
