### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CoreLation1** [Pan4ur/ThunderHack-Recode#320]
пытаюсь забилдить но пишет ошибку что файл поврежден пытался переустанавливать и делать всё другое не помогает

![Снимок экрана 2024-05-29 223948](https://github.com/Pan4ur/ThunderHack-Recode/assets/171115660/81f86355-ff4c-4dfa-800d-fc2b8c2409af)

**Comment by dest4590** [comment]
удали папку build, и запусти gradle clean

**Comment by CoreLation1** [comment]
если бы я мог это сделать
![Снимок экрана 2024-05-30 115242](https://github.com/Pan4ur/ThunderHack-Recode/assets/171115660/657f9066-2567-40ff-857e-29a5f7110ef8)
![Снимок экрана 2024-05-30 115248](https://github.com/Pan4ur/ThunderHack-Recode/assets/171115660/1a4bbfdd-3912-4370-9e22-3011daa347ed)

**Comment by CoreLation1** [comment]
или какой именно build удалить?

**Comment by dest4590** [comment]
хз, попробуй переклонить с гитхаба и забилдить заново

**Comment by Pan4ur** [comment]
а мне кажется рип

**Comment by CoreLation1** [comment]
> а мне кажется рип

??

**Comment by CoreLation1** [comment]
> хз, попробуй переклонить с гитхаба и забилдить заново

ты пытался что то делать с сурсами?

**Comment by dest4590** [comment]
> > хз, попробуй переклонить с гитхаба и забилдить заново
> 
> ты пытался что то делать с сурсами?

да, даже пулл реквесты делал

**Comment by dest4590** [comment]
просто попробуй удалить всё, и скачать заново

**Comment by CoreLation1** [comment]
раз 10 пытался уже и с хаба и там где release нигде не получается

**Comment by CoreLation1** [comment]
> > > хз, попробуй переклонить с гитхаба и забилдить заново
> > 
> > 
> > ты пытался что то делать с сурсами?
> 
> да, даже пулл реквесты делал

мб просто скинешь свои сурсы? просто сурсы других софтов работают прекрасно

**Comment by dest4590** [comment]
https://github.com/dest4590/ThunderHack-Recode

**Comment by CoreLation1** [comment]
> https://github.com/dest4590/ThunderHack-Recode

не всё равно ошибка я уже и idea пытался переустанавливать хз

**Comment by CoreLation1** [comment]
> > [](https://github.com/dest4590/ThunderHack-Recode)
> 
> не всё равно ошибка я уже и idea пытался переустанавливать хз

что именно рип?

**Comment by CoreLation1** [comment]
> а мне кажется рип

что именно рип?

**Comment by Pan4ur** [comment]
все рип

**Comment by Pan4ur** [comment]
просто рипчанский

**Comment by CoreLation1** [comment]
> просто рипчанский

прям всё всё? или всем всем?

**Comment by Pan4ur** [comment]
прям попадос рипандос

**Comment by 06ED** [comment]
Пиздец

**Comment by CoreLation1** [comment]
> Пиздец

чему пиздец?

**Comment by CoreLation1** [comment]
> прям попадос рипандос

вот прям на столько?

**Comment by Pan4ur** [comment]
Дааааа прям рипдец

**Comment by dest4590** [comment]
> Дааааа прям рипдец

вообще ужас просто прям риппп
