### ISSUE TITLE
Vulcan Bypass (NoSlow, Velocity, Speed, WaterSpeed - Jesus, etc.)

### ISSUE THREAD

**Issue by Eblan4ikRK** [Pan4ur/ThunderHack-Recode#335]

**Comment by delyfss4796** [comment]
There are no noslow checks in vulcan and for velo you can use cancel or oldgrim

**Comment by Eblan4ikRK** [comment]
> There are no noslow checks in vulcan and for velo you can use cancel or oldgrim

nah, noslow is get flagging and after 3-5 flag i get kicked by vulcan, with velocity is working 50/50 kick if you get so much of flags but if you in netherite armor not kicking

**Comment by delyfss4796** [comment]
@Pan4ur ало еблан закрой хуйню чел насарл
