### ISSUE TITLE
Добавить дистанцию аттаки для элитр

### ISSUE THREAD

**Issue by t1mrush** [Pan4ur/ThunderHack-Recode#348]
**Is your feature request related to a problem? Please describe.**
Дистанция аттаки для элитр нужна, потому что на элитрах можно легитно ударить только за 1.5 (но на некоторых серверах даже не проходят удары с range 1.5), поэтому я хочу чтобы добавили дистанцию аттаки для элитр

**Describe the solution you'd like**
Добавить в Aura параметр ElytraRange.

**Comment by ItzRealFemboy** [comment]
сделано

**Comment by Pan4ur** [comment]
хуелано
