### ISSUE TITLE
Джамп сёрклы не могут найти картинку джамп сёрклов и это засоряет чат

### ISSUE THREAD

**Issue by CawtMeoow** [Pan4ur/ThunderHack-Recode#351]
Включи джамп сёрклы и будет что типо нету их в паке, но они как бы есть если попрыгать
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/170893126/a5ddf5d6-bcf8-4c25-b985-ab65287397af)

**Comment by t1mrush** [comment]
поменяй режим в jump circle с custom на другой
/close

**Comment by CawtMeoow** [comment]
у меня дефолт стоит
