### ISSUE TITLE
Баг с таргет худом

### ISSUE THREAD

**Issue by UltraBebra228** [Pan4ur/ThunderHack-Recode#357]
![Снимок экрана 2024-06-08 131832](https://github.com/Pan4ur/ThunderHack-Recode/assets/138705298/91e8a515-a11f-4831-bb9e-22a62057037a)

**Comment by Pan4ur** [comment]
@ItzRealFemboy попался

**Comment by ItzRealFemboy** [comment]
а это что а это как,это с хелбустом?

**Comment by ItzRealFemboy** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/74070886/aa246020-62ab-464d-a18b-9ed13f4b067f)
что у тебя за эффекты,я думал хелзбуст но  у меня всё норм с ним

**Comment by ItzRealFemboy** [comment]
что у тебя за эффекты?я думал хелзбуст но с ним всё норм
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/74070886/602d47ff-ffde-4def-82b4-6cf32c835a86)

**Comment by ItzRealFemboy** [comment]
бллавячвоалявоалячачяачя я кажется понял щас надо на фт для теста зайти

**Comment by ItzRealFemboy** [comment]
или не надо

**Comment by ItzRealFemboy** [comment]
всё понял прикол ща буду фиксить

**Comment by ItzRealFemboy** [comment]
фикс сделан скоро панчур его примет

**Comment by ItzRealFemboy** [comment]
а ну хули закрыть можно же
