### ISSUE TITLE
rustex/rustme version of thunderhack

### ISSUE THREAD

**Issue by GamerGuy1717** [Pan4ur/ThunderHack-Recode#360]
featuring aimbot(with client and silent rotation, bullet drop prediction for bow and prediction for guns),autopeek,handtranslate,flight(basically spider but for rustme/rustex) and timer. and thats it idk what to ask more, i will edit this or respond to ur comments if i will come back in a few months days or weeks

**Comment by Pan4ur** [comment]
No

**Comment by GamerGuy1717** [comment]
😭
