### ISSUE TITLE
Кривая сетка hud

### ISSUE THREAD

**Issue by dest4590** [Pan4ur/ThunderHack-Recode#385]
при размещении arraylist в углу экрана проиходят баги отображения 

https://github.com/Pan4ur/ThunderHack-Recode/assets/80628386/e5ef315d-b331-416f-b4e5-12ad441afd5d

**Comment by Slieko** [comment]
хуй_мелок

**Comment by dest4590** [comment]
> хуй_мелок
🤑

**Comment by Pan4ur** [comment]
фиксед

**Comment by dest4590** [comment]
спс брад
