### ISSUE TITLE
Issue when trying to make a command in an addon.

### ISSUE THREAD

**Issue by LockScript** [Pan4ur/ThunderHack-Recode#405]
**Describe the bug**
A clear and concise description of what the bug is. It has so many errors, and you cannot make a command like you do in the normal client.

'executeBuild(LiteralArgumentBuilder<ServerCommandSource>)' in 'com.example.commands.ExampleCommand' clashes with 'executeBuild(LiteralArgumentBuilder<class_2172>)' in 'thunder.hack.cmd.Command'; both methods have same erasure, yet neither overrides the other

Method does not override method from its superclass

```java
package com.example.commands;

import com.mojang.brigadier.builder.LiteralArgumentBuilder;
import net.minecraft.server.command.ServerCommandSource;
import net.minecraft.text.Text;
import net.minecraft.util.Formatting;
import org.jetbrains.annotations.NotNull;
import thunder.hack.ThunderHack;
import thunder.hack.cmd.Command;

import java.util.concurrent.atomic.AtomicBoolean;

import static com.mojang.brigadier.Command.SINGLE_SUCCESS;

public abstract class ExampleCommand extends Command {
    public ExampleCommand() {
        super("help");
    }

    @Override
    public void executeBuild(@NotNull LiteralArgumentBuilder<ServerCommandSource> builder) {
        builder.executes(context -> {
            sendMessage("Commands: \n");

            AtomicBoolean flip = new AtomicBoolean(false);

            ThunderHack.commandManager.getCommands().forEach(command -> {
                        context.getSource().getPlayer().sendMessage(Text.of(
                                (flip.get() ? Formatting.LIGHT_PURPLE : Formatting.DARK_PURPLE)
                                        + ThunderHack.commandManager.getPrefix()
                                        + (flip.get() ? Formatting.AQUA : Formatting.DARK_AQUA)
                                        + command.getName()
                                        + (command.getAliases().isEmpty() ? "" : " (" + command.getAliases() + ")")
                                        + Formatting.DARK_GRAY + " -> "
                                        + (flip.get() ? Formatting.WHITE : Formatting.GRAY)
                                        + command.getDescription()
                        ));
                        flip.set(!flip.get());
                    }
            );

            return SINGLE_SUCCESS;
        });
    }
}
```

**Comment by Slieko** [comment]
нахуя вам эти аддоны, лучше форканите репо и не ебите себе мозги

**Comment by LockScript** [comment]
> нахуя вам эти аддоны, лучше форканите репо и не ебите себе мозги
Вау, спасибо за помощь.

**Comment by LockScript** [comment]
Очевидно, система аддонов глючная, ее реализовали буквально час назад.

**Comment by Pan4ur** [comment]
> нахуя вам эти аддоны, лучше форканите репо и не ебите себе мозги

И потом добавлять каждый фикс коих в день выходит по 5 штук :roflan_ebalo:

**Comment by Slieko** [comment]
бля, чел сам сделал аддоны и теперь у него нихуя не работает :suka_che_on_neset:

**Comment by LockScript** [comment]
да, но я не создавал систему команд.


> бля, чел сам сделал аддоны и теперь у него нихуя не работает :suka_che_on_neset:

**Comment by Pan4ur** [comment]
Я не делал аддоны :facepalm2:

**Comment by Slieko** [comment]
зачем ты кста с другого аккаунта пишешь?

**Comment by LockScript** [comment]
> Я не делал аддоны :facepalm2:

😂хорошо, ты прав, я рассмотрю этот вопрос.

**Comment by LockScript** [comment]
> зачем ты кста с другого аккаунта пишешь?

У меня две сессии в двух разных браузерах, лол, даже не заметил.

**Comment by Slieko** [comment]
> 
> У меня две сессии в двух разных браузерах, лол, даже не заметил.
> 
:emoji_8:

**Comment by LockScript** [comment]
The issue was with the addon template, not thunderhack. This problem has been resolved.
Проблема была в шаблоне аддона, а не в Thunderhack. Эта проблема была решена.
