### ISSUE TITLE
config folder bug

### ISSUE THREAD

**Issue by xzeeyy** [Pan4ur/ThunderHack-Recode#419]
I just installed the cheat, downloaded the config file, installed it, and after installing it, crystal aura did not put it while eating golden apples, I tried every mode, it still does not work, I deleted the thunderhack file, it was fixed, I restored the config.th I made first, it broke again, then I deleted it again, I made config from scratch, it still does not put crystalaura while eating golden apples.

**Comment by Pan4ur** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/82473048/b12f79b0-e51a-4f76-a15b-0fc5dd3cf191)

**Comment by xzeeyy** [comment]
I tried every mode and it doesn't work at all.

**Comment by xzeeyy** [comment]
it doesn't work
