### ISSUE TITLE
Scaffload有视角抽搐的bug(NCP or StrictNCP)

### ISSUE THREAD

**Issue by emmmluxin** [Pan4ur/ThunderHack-Recode#420]
1.20.6 Fabric ThunderHack 
-
When using the Scaffload module
When NCP or StrictNCP is selected, the camera twitches will occur
(GirmAC doesn't have such a problem)

1. Go to Scaffload
2. Click on NCP or StrictNCP
3. Build blocks

**Comment by liquidbounce-thebestclient** [comment]
chinese? this client is less cn user , I did not see any cn user except you report bug

好吧我也是中国人，我的端加载不出来，是需要vpn吗?

**Comment by emmmluxin** [comment]
> 中文？这个客户端是较少的cn用户，除了你报告错误之外，我没有看到任何cn用户
> 
> 好吧，我也是中国人，我的端加载不出来，是需要vpn吗？

This client doesn't require a VPN, and you can't open it probably because of insufficient memory allocation

这玩意需要啥vpn,在线人数都是p的，还有也有一个中文的isuess
