### ISSUE TITLE
баги с гуи

### ISSUE THREAD

**Issue by kanderplay** [Pan4ur/ThunderHack-Recode#447]
У меня есть 2 проблемы

1) при заходе, меню обновлений на весь ебучий экран
![2024-07-30_19 53 46](https://github.com/user-attachments/assets/dbe539ab-1cd8-4577-8718-4c5e7374c5ca)
2) когда открываю гуи, он на весь экран нахуй, и не все вмещается, это еще цветочки, когда я все расположил, приведу пример
![2024-07-30_19 54 34](https://github.com/user-attachments/assets/2c3d88c8-4639-4f7d-b55e-a73e2f54d191)
и выхожу с гуи, и потом захожу, то у меня блять опять все сетается нахуй
![2024-07-30_19 54 05](https://github.com/user-attachments/assets/952daac2-9556-4b86-893f-4c9c631e8111)
безумно бесит, а еще бесит что клиент находится прямо на виапоне, я жду ответа, как решить эту проблему
версия: 1.21, ниже тоже также, у моих знакомых также

**Comment by ChamsBypass** [comment]
поставь в настройках майна размер интерфейса на 2
