### ISSUE TITLE
Keybinds for individual modules

### ISSUE THREAD

**Issue by Elitaria** [Pan4ur/ThunderHack-Recode#450]
**Is your feature request related to a problem? Please describe.**
Its difficult to quickly toggle modules in the gui, and it can often be dangerous in a pvp situation or just for overall convenience.

**Describe the solution you'd like**
A simple way to add a keybind to a module, such as meteor client's keybind section

**Comment by Pan4ur** [comment]
1. Press middle mouse button on the module
2. Be shoked
