### ISSUE TITLE
please fix the lag on pojavlaucher 

### ISSUE THREAD

**Issue by Thinhdzzvl** [Pan4ur/ThunderHack-Recode#453]
I really want to use it so please fix the lag  
THANKS FOR READING

**Comment by 2young2care** [comment]
dịch The problem here is not whether the phone is strong or weak, but the problem here that makes the phone lag when playing thunderhack is due to the shader/visual/satin
 từ Tiếng Anh

**Comment by 2young2care** [comment]
The problem here is not whether the phone is strong or weak, but the problem here that makes the phone lag when playing thunderhack is due to the shader/visual/satin

**Comment by Thinhdzzvl** [comment]
How do I remove the visual and satin shaders?

**Comment by Thinhdzzvl** [comment]
please remove or reduce them I can only play at 2 fps :(

**Comment by 2young2care** [comment]
> please remove or reduce them I can only play at 2 fps :(

they won't delete it as deleting some things in thunderhack just makes thunderhack less functional. instead of deleting, save money and buy a new computer
