### ISSUE TITLE
Fix lag

### ISSUE THREAD

**Issue by NhutQuangg** [Pan4ur/ThunderHack-Recode#454]
.
Can you fix the Lag Thunder Hack so everyone can play on Pojavlaucher?

**Comment by 2young2care** [comment]
No

**Comment by 2young2care** [comment]
Remove satin

**Comment by 2young2care** [comment]
The problem here is not whether the phone is strong or weak, but the problem here that makes the phone lag when playing thunderhack is due to the shader/visual/satin
