### ISSUE TITLE
There is no game sound in version 1.20.4

### ISSUE THREAD

**Issue by ganyemuyouji** [Pan4ur/ThunderHack-Recode#456]
**Describe the bug**
After starting the game, there may be some sounds that cannot be heard, such as breaking blocks, eating food, etc. This phenomenon is particularly evident on the server, and during the process of loading material packages, it may get stuck in the loading interface.

**To Reproduce**
There is no sound after entering the game.

**Comment by averytnestlima** [comment]
thunderhack 1.20.4 not updated, use thunderhack 1.21

**Comment by averytnestlima** [comment]
to fix this, disable module "OptifineCapes"
