### ISSUE TITLE
Please add a Velocity Jump

### ISSUE THREAD

**Issue by Boneshadow** [Pan4ur/ThunderHack-Recode#46]
**Please add Velocity mod Jump or JumpReset 
It will really boost the gameplay 
Here are the sources of something similar** 
**[Sources](https://github.com/SkidderMC/FDPClient/blob/89e2ad5fca2f8e3ef956b723db0278d9be1520dd/src/main/java/net/ccbluex/liquidbounce/features/module/modules/combat/velocitys/vanilla/JumpVelocity.kt)**

**Comment by Pan4ur** [comment]
Ok, it'll be in the next update
