### ISSUE TITLE
No texture bug 😢

### ISSUE THREAD

**Issue by NotBlack777** [Pan4ur/ThunderHack-Recode#460]
**Describe the bug** 
No texture bug

**To Reproduce**
Whenever I try to open like pika network(1.20.4 server) I don't have any texture it comes after like 5 mins after and when I had no thunder client it was instant pls try to fix that

**Expected behavior**
When I join a server it takes time to load texture that is normal textures

**Screenshots**
![Screenshot_20240812-012230](https://github.com/user-attachments/assets/a685af40-996b-4611-a297-5f457da36685)
![Screenshot_20240812-011339~2](https://github.com/user-attachments/assets/e5f705e0-a80b-476d-b7c6-d725e12912e6)
![Screenshot_20240812-011333~2](https://github.com/user-attachments/assets/f8b47ad0-2931-48df-b298-c33cd0bb93a8)
![Screenshot_20240812-011322~2](https://github.com/user-attachments/assets/4dd3b730-30ba-421c-a34a-f0b69ffaf7ee)
![Screenshot_20240812-011313~2](https://github.com/user-attachments/assets/c058c93c-048b-4263-824e-a3a155f230ef)
![Screenshot_20240812-011256~2](https://github.com/user-attachments/assets/937f1819-c715-4d59-8aa6-633411ee99f2)
![Screenshot_20240812-011149~2](https://github.com/user-attachments/assets/470e4ead-123a-4025-988f-bd84c0f42626)
![Screenshot_20240812-011222~2](https://github.com/user-attachments/assets/8abd2ac5-1163-48fa-be49-7c2e5d622592)
![Screenshot_20240812-011230~2](https://github.com/user-attachments/assets/a4a753ab-9914-407d-8595-8d946b7363b5)
![Screenshot_20240812-011240~2](https://github.com/user-attachments/assets/b64d83d5-3e34-473b-905f-ce20e4ab1afc)
https://github.com/user-attachments/assets/b4f7ebe9-d576-4b1c-ab80-fbbb264b4a8a
These are ss of my mods folder and my resource pack folder and whats happens
**Additional context**
I am on mobile I play on MotorolaG52
I play on pojav launcher with 6gb ram
Pls tell me if u want anything more 🙏 

Much appreciated 
Ty ❤️

**Comment by lolbatch** [comment]
how do you expect for your phone to handle that..
