### ISSUE TITLE
thunderhack doesnt work

### ISSUE THREAD

**Issue by haxur730** [Pan4ur/ThunderHack-Recode#477]
[latest.log](https://github.com/user-attachments/files/16689386/latest.log)
thunderhack still crashed, i tried to change versions of minecraft and also mods but it's still doesnt work

**Comment by Pan4ur** [comment]
Your thunderhack is old as shit, try to update

**Comment by SowHaxks** [comment]
whats rust_launcher and why is it in feather 1.20.4 + doesnt feather use fabric?
