### ISSUE TITLE
World loading about 2 minutes then just world without anything

### ISSUE THREAD

**Issue by sergeynosov13** [Pan4ur/ThunderHack-Recode#478]
World loading about 2 minutes then just world without anything
![image](https://github.com/user-attachments/assets/b85bbd80-dfd8-4ca1-aa0a-9602cfed0bab)
![image](https://github.com/user-attachments/assets/2b4331af-9626-431a-b9d5-b9c74b365dcf)
in 1.21

**Comment by ChamsBypass** [comment]
попробуй содиум

**Comment by RedHolms** [comment]
умер со фрикамом включенным значит, или на сервер перезашёл. в главном меню открой кликгуи и выключи фрикам
