### ISSUE TITLE
Absolute russian cringe

### ISSUE THREAD

**Issue by EurekaEffect** [Pan4ur/ThunderHack-Recode#48]

**Comment by 06ED** [comment]
Questions?

**Comment by rusnuker** [comment]
And yet you had to open an issue to leave your comment. If you don't like something, you should just move on. But now this situation is stuck in your head! Enjoy your suffering

**Comment by Pan4ur** [comment]
Ахуеть как похуй

**Comment by EurekaEffect** [comment]
> And yet you had to open an issue to leave your comment. If you don't like something, you should just move on. But now this situation is stuck in your head! Enjoy your suffering

![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/58750228/e173f26d-450a-4525-9c75-b4c625c73c96)

**Comment by rusnuker** [comment]
> > And yet you had to open an issue to leave your comment. If you don't like something, you should just move on. But now this situation is stuck in your head! Enjoy your suffering
> 
> ![image](https://user-images.githubusercontent.com/58750228/266130919-e173f26d-450a-4525-9c75-b4c625c73c96.png)

what in the fuck :skull:

**Comment by 06ED** [comment]
хохла спросить забыли

**Comment by EurekaEffect** [comment]
> хохла спросить забыли

![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/58750228/dba36952-d655-40bd-8812-20a36d108668)
