### ISSUE TITLE
на холиворлде кикает, когда даю криты

### ISSUE THREAD

**Issue by tapo4ek21** [Pan4ur/ThunderHack-Recode#483]
![image](https://github.com/user-attachments/assets/d5006f27-99c2-48b4-b982-3cbe56184fdd)

на холике лайт кикает, когда даю кому нибудь крит. на классике такой хуйни нет чо делать
[disconnect-2024-08-26_23.01.38-client.txt](https://github.com/user-attachments/files/16753202/disconnect-2024-08-26_23.01.38-client.txt)

**Comment by lolbatch** [comment]
это проблема viafabric
