### ISSUE TITLE
yo i edited thunder hack you want it it has a better ui then before

### ISSUE THREAD

**Issue by espero-dev** [Pan4ur/ThunderHack-Recode#49]
i made changes to the ui and also added a ui tab for i think adding/finding custom modules people can make for it

**Comment by Pan4ur** [comment]
Cool

**Comment by espero-dev** [comment]
yea im working on a couple more things too it ill make the code public and downloadable when im done with my edits to it so people can explore it more and edit it more but most people are going to skid it but theirs one video of me using it online it only had one ui change i think but theirs a friend that knows the hole ui and stuff we test it and we working on it quite a bit

**Comment by espero-dev** [comment]
but also you might be able to find the video on my channel if i did have a video about it https://youtube.com/@espero_dev
