### ISSUE TITLE
Крашит на Pojav launcher

### ISSUE THREAD

**Issue by SRTz123s** [Pan4ur/ThunderHack-Recode#493]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
[latestlog.txt](https://github.com/user-attachments/files/16804966/latestlog.txt)

**Additional context**
Add any other context about the problem

**Comment by SRTz123s** [comment]
[latestlog.txt](https://github.com/user-attachments/files/16804971/latestlog.txt)

**Comment by alexsovi** [comment]
> (Permission denied)
selinux момент, ищи фикс в гугле
