### ISSUE TITLE
автосво/autoswap

### ISSUE THREAD

**Issue by tapo4ek21** [Pan4ur/ThunderHack-Recode#496]
функция, которая позволяет по нажатию бинда свапать предмет в левой руке на другой

**Comment by Pan4ur** [comment]
Есть в AutoTotem в режиме Totem

**Comment by tapo4ek21** [comment]
а если надо что-то шар на шар свапать, что делать?

**Comment by Pan4ur** [comment]
ну так там выбор есть

**Comment by tapo4ek21** [comment]
![image](https://github.com/user-attachments/assets/307f764d-98e8-4a6b-85ac-9fba62d383bc)
там только эти 4 варианта

**Comment by Pan4ur** [comment]
ну

**Comment by Pan4ur** [comment]
ball это шар, вот и выбирай шар на щит, шар на гепл, шар на тотем или щит на гепл

**Comment by tapo4ek21** [comment]
шар на шар я хотел😭

**Comment by tapo4ek21** [comment]
сделай еще сохранение зачарованных тотемов
