### ISSUE TITLE
doesn't launch

### ISSUE THREAD

**Issue by dtbbbb** [Pan4ur/ThunderHack-Recode#498]
**Describe the bug**
it doesn't let me launch

**To Reproduce**
launch the latest version of 1.20.6

**Expected behavior**
IDK

**Screenshots**
https://mclo.gs/HVCJuQJ

**Additional context**
HELP

**Comment by Pan4ur** [comment]
Update to the latest release

**Comment by I-No-oNe** [comment]
Please check mods compatability

**Comment by I-No-oNe** [comment]
@Pan4ur close issue?
