### ISSUE TITLE
Pan4ur Авто тотем везде так делает советую изменить EZbowPOP на ориг как в риче или акриене например. И вернуть передвежение вкладок в ClickGui как в тх+

### ISSUE THREAD

**Issue by fdgfhdfhdhth** [Pan4ur/ThunderHack-Recode#50]

**Comment by fdgfhdfhdhth** [comment]
Кста

**Comment by fdgfhdfhdhth** [comment]
Обнови ClickGui  убери ThunderGui а то диз баланс + Клик Гуи старый

**Comment by dog130cat130** [comment]
ХАХАХАХАХ

**Comment by Pan4ur** [comment]
> ХАХАХАХАХ, дизбаланс изза ThunderGui, пиздец

Забей это игрок фанигейма

**Comment by dog130cat130** [comment]
> > ХАХАХАХАХ, дизбаланс изза ThunderGui, пиздец
> 
> Забей это игрок фанигейма

Правду говорят: кристалка стала умнее игроков фг

**Comment by 06ED** [comment]
Почему в реакциях нельзя черепа ставить?
