### ISSUE TITLE
Is ThunderHack now supported with PojavLauncher?

### ISSUE THREAD

**Issue by ImTou** [Pan4ur/ThunderHack-Recode#503]
Hi ThunderHack team,

I'm interested in using ThunderHack with PojavLauncher, a popular Minecraft launcher for Android and other platforms. I was wondering if ThunderHack is currently compatible with PojavLauncher or if there are any plans to add support for it in the future.

I've tried searching the documentation and issues, but couldn't find any information on this topic. If it's not currently supported, are there any workarounds or alternative launchers that I can use with ThunderHack?

**Comment by nikitadan4pi** [comment]
No, It can work only on SnapDragon and Zink. But other phones not support hack

**Comment by SowHaxks** [comment]
https://github.com/CobraaxNXGHT/Thunderhack-Pojav This may work? It is a fork of Thunderhack that claims to support pojav. Not sure if it is a rat though.

**Comment by ImTou** [comment]
Okay Thanks
