### ISSUE TITLE
Hwhelper

### ISSUE THREAD

**Issue by tapo4ek21** [Pan4ur/ThunderHack-Recode#505]
функция для холиворлда
чтота типа фт хелпера, но под хв
чтобы можно было юзать взрывные трапки, станы и т.д. из инвентаря

**Comment by kirillmegapenir** [comment]
Чит опенсурс делай сам

**Comment by RaZrad** [comment]
Да, имба идея пдпжпжп

**Comment by RaZrad** [comment]
Up

**Comment by ChamsBypass** [comment]
хв хуйня так что закрываем
