### ISSUE TITLE
Save зачарованных тотемов

### ISSUE THREAD

**Issue by RaZrad** [Pan4ur/ThunderHack-Recode#506]
В автототеме сделать чекбокс сохранять зачарованные. Ну типо в чите есть обходы под фт/хв, а этой функции нету

**Comment by kirillmegapenir** [comment]
Чит опенсурс делай сам

**Comment by RaZrad** [comment]
Пошел нахуй

**Comment by ChamsBypass** [comment]
фт/хв помойки так что можно закрывать
