### ISSUE TITLE
[1.21] Xray doesn't work

### ISSUE THREAD

**Issue by chadlrnsn** [Pan4ur/ThunderHack-Recode#516]
**Describe the bug**
I don't know what to describe here except that xray doesn't work.

**To Reproduce**
Enable xray at fabric & sodium + optifine

**Screenshots**
Enabled
![Enabled](https://i.imgur.com/r225Ci2.png)
Disabled
![Disabled](https://i.imgur.com/DyGLYZf.png)

**Additional context**
Version 1.21 Fabric optifine sodium

**Comment by SowHaxks** [comment]
Maybe the server your in has anti-xray?

**Comment by chadlrnsn** [comment]
I would mention this if I were on a server, but unfortunately it's on a local server

**Comment by chadlrnsn** [comment]
ok i fixed this
![IMG](https://i.imgur.com/vg4Wume.png)
something in this mods conflicting with cheat
| mods | high risk of conflict |
|----|----|
| DistantHorizons-2.2.0-a-1.21.1-neo-fabric.jar | ✅ |
| indium-1.0.35+mc1.21.jar | ✅ |
| iris-fabric-1.8.0-beta.4+mc1.21.1.jar | ✅ |
| sodium-fabric-0.6.0-beta.2+mc1.21.1.jar | ✅ |
| WI-Zoom-1.5-MC1.21.jar | ❌ |
