### ISSUE TITLE
Сделать для пакет флая другие числы в факторе

### ISSUE THREAD

**Issue by NCPUser** [Pan4ur/ThunderHack-Recode#6]
не 2.0 и 3.0 и т.д а 1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.0 и т.д

**Comment by AquaMinerale2b2t** [comment]
если бы паркет не был бы спащен с хуй пойми чего, то был бы нормальный цикл фактора, а так никак - настройка целочисленная. 
совет панчуру: для дробынх чисел фактора один дополнительный набор паркетов отправляется в проценте тиков равному дробной части фактора * 100% т.е при факторе 2.6 в 4/10 тиков отправляется 2 набора паркетов в тик, а в 6/10 тиков отправляется 3 набора паркетов

**Comment by AquaMinerale2b2t** [comment]
![image](https://github.com/Pan4ur/ThunderHack-Recode/assets/96651128/2d781d6c-8c9b-4ac2-bfd3-55b48200521d)

**Comment by Pan4ur** [comment]
1.2b230723
