### ISSUE TITLE
Новое

### ISSUE THREAD

**Issue by fdgfhdfhdhth** [Pan4ur/ThunderHack-Recode#70]
Добавить AutoDuel
Добавить AntikickAfk
Добавить Criticals - FunTime, rw
Добавить Jesus с обходами FunTime, HollyWorld, FunnyGame(база) Rw
И спидов по больше)

**Comment by rusnuker** [comment]
добавь это сам

**Comment by Broder474** [comment]
> добавь это сам
![my-reaction-to-that-information-meme-my-reaction-to-that-information](https://github.com/Pan4ur/ThunderHack-Recode/assets/53940869/5ec89a92-b317-4044-b6ed-b1f439a1e4a4)
