### ISSUE TITLE
netty issue when connecting to servers on viafabricplus

### ISSUE THREAD

**Issue by Epic62790** [Pan4ur/ThunderHack-Recode#79]
a netty issue where it says that it automatically has disconnected this session and it dosent work it works with 1.12.2 but lagsback really bad

**Comment by Epic62790** [comment]
ive tried 1.20.1, 1.19, and i get the same netty issue

**Comment by Epic62790** [comment]
please fix i cant even connect to servers with this hack it just says user has been disconnected with some error stuff

**Comment by Epic62790** [comment]
smh

**Comment by dog130cat130** [comment]
https://github.com/ViaVersion/ViaFabricPlus/issues/253
