### ISSUE TITLE
How to move the hud elements?

### ISSUE THREAD

**Issue by HenryXiaoYang** [Pan4ur/ThunderHack-Recode#90]
I did't find any config about position of the elements, I tried drag the element and it didn't work. How to move the elements of hud?

Thx for the excellent mod.

**Comment by 06ED** [comment]
It is linux issues mb will fixed

**Comment by Pan4ur** [comment]
> It is linux issues mb will fixed

I don't think so. I just checked for KALI and it's fine

**Comment by HenryXiaoYang** [comment]
macos?? plz
