### ISSUE TITLE
Best autocrystal

### ISSUE THREAD

**Issue by Ryner32** [Pan4ur/ThunderHack-Recode#93]
Сори за фпс прога хуйня + кристалка не хило жрëт

**Comment by Ryner32** [comment]
Ez

**Comment by Ryner32** [comment]
Брух где моë видео

**Comment by Ryner32** [comment]
Блять ебаный гитхаб, ну короче кристалка не ставит крисы типо вобще, кфг у меня ваш встроеный, пинг 80-120, фпс 90

**Comment by 06ED** [comment]
Какой сервер?
Какой конфиг?

**Comment by Pan4ur** [comment]
На сс вчера поменяли античит, для повышения фпс рекомендуется исользовать Multithreading. Пожалуйста не открывайте issue если не умеете настраивать клиенты.
